### ISSUE TITLE
TypeError: Cannot assign to read only property 'name' of function

### ISSUE THREAD

**Issue by kildus** [luscus/geojson.lib.routeboxer#2]
I got TypeError:

d:\j\node_modules\geojson.lib\lib\tools.js:285
  typeProvider.name = 'get'+type;
                    ^
TypeError: Cannot assign to read only property 'name' of function (coordinates,
bbox, precision) {
    return getGeoJson(type, coordinates, bbox, precision);
  }
    at typeIterator (d:\j\node_modules\geojson.lib\lib\tools.js:285:21)
    at Array.forEach (native)
    at Object.<anonymous> (d:\j\node_modules\geojson.lib\lib\tools.js:280:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\j\node_modules\geojson.lib\lib\geojson.lib.js:9:18
)

for example https://github.com/luscus/geojson.lib.routeboxer/blob/master/test/simple.js

**Comment by luscus** [comment]
This fix should do it, I will release it with  luscus/geojson.lib@0.0.10 today and bump this library with the right dependency.

This geojson.lib.routeboxer package and the luscus/geojson.lib will be redesigned soon.
I don't use them right now, and they've been somewhat sloppy about them
